const express = require("express")
const user = express.Router()
const addhome = require("../Controllers/dashboard/addhomeController")
const { client } = require("../database/connection")
const gethomes = require("../Controllers/Users/homesControllers")
const authMiddleware = require("../Middleware/authMiddleware")
const searchHomes = require("../Controllers/Users/SearchController")
const upload = require("../Middleware/upload")
const categories = require("../Controllers/Users/Categories")
const GetIndividualHomes = require("../Controllers/Users/GetSingleHome")
const contact  = require("../Controllers/Users/Contact")

user.post("/addhome" ,authMiddleware , upload.array("images" , 5) ,  addhome )
user.get("/" , gethomes )
user.get("/home/:id" , GetIndividualHomes )
user.post("/search" , searchHomes)
user.post("/categories" , categories)
user.post("/contact" , contact )
module.exports = user