require("dotenv").config()
const express = require("express")
const cors = require("cors")
const connectDb = require("./database/mongoose")
const app = express()


app.use(cors())
app.use(express.json())
app.use("/uploads" , express.static("uploads"))

const userget = require("./routes/homes")
const userpost = require("./routes/users")
const deleteHome  = require("./routes/Delete")
const updatehome = require("./routes/Update")
const wishlist = require("./routes/wishlist")
const auth = require("./routes/auth")
const dashboard = require("./routes/dashboard")
app.use(userget)
app.use(userpost)
app.use(deleteHome)
app.use(updatehome)
app.use(wishlist)
app.use(auth)
app.use(dashboard)
connectDb()
app.listen(4090)  
